tunnel: f64de399-2e24-4c0c-8c40-a1bb95dee012
credentials-file: /etc/cloudflared/f64de399-2e24-4c0c-8c40-a1bb95dee012.json

ingress:
  - hostname: api.wattsun.co.ke
    originRequest:
      noTLSVerify: true
    service: http://192.168.1.52:3001

  - service: http_status:404
